# --- CONFIGURATION FILE ---

# 1. UPSTOX API SETTINGS
UPSTOX_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI3NkFGMzUiLCJqdGkiOiI2OTZkOWUwMjNkODJjNDc2OGI2OGQ0OWEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc2ODc5MTU1NCwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzY4ODYwMDAwfQ.jsXrdkm2F3IxlBN_ccRwBZYJ0-FoDDu34yG0LfLa02k"

# 2. TRADING CONFIG
# For Upstox, Symbols look like: "NSE_INDEX|Nifty 50" or "NSE_EQ|RELIANCE"
# Use "NSE_INDEX|Nifty 50" for Nifty, "NSE_INDEX|Nifty Bank" for Bank Nifty
SYMBOL = "NSE_INDEX|Nifty 50"
EXPIRY_DATE = "2025-05-29" # Format: YYYY-MM-DD.
RISK_FREE_RATE = 0.07
