# --- CONFIGURATION FILE ---

# 1. UPSTOX API SETTINGS
UPSTOX_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI3NkFGMzUiLCJqdGkiOiI2OTZjYTgwNmNkNDg2ZjY1YmRlYTEyNzIiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc2ODcyODU4MiwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzY4NzczNjAwfQ.qK_2Dfx26ZjFD7qaFYwu9G_OYWvJsEMy49_I9r0in1A"

# 2. TRADING CONFIG
# For Upstox, Symbols look like: "NSE_INDEX|Nifty 50" or "NSE_EQ|RELIANCE"
# Use "NSE_INDEX|Nifty 50" for Nifty, "NSE_INDEX|Nifty Bank" for Bank Nifty
SYMBOL = "NSE_INDEX|Nifty 50"
EXPIRY_DATE = "2025-05-29" # Format: YYYY-MM-DD.
RISK_FREE_RATE = 0.07
